#!/usr/bin/env python

import sys, getopt, json

def usage(name):
  print 'Usage: %s -l [key1:key2] -o [field1] -o [field2] ... -o [fieldN]' % name

def main(argv):
  fields = []
  nodeAddr = ''
  try:
    opts, args = getopt.getopt(argv[1:],'hl:o:')
  except getopt.GetoptError:
    usage(argv[0])
    sys.exit(2)
  for opt, arg in opts:
    if opt in ('-h'):
      usage(argv[0])
      sys.exit()
    elif opt in ('-o'):
      fields.append(arg)
    elif opt in ('-l'):
      nodeAddr = arg
  if not nodeAddr or not fields:
    usage(argv[0])
    sys.exit(1)
  pipe = sys.stdin.read()
  try:
    payload = json.loads(pipe)
  except:
    print 'Err: unable to parse JSON'
    sys.exit(1)
  nodeList = nodeAddr.split(':')
  data = []
  for i in nodeList:
    if i in payload.keys():
      data = payload[i]
    else:
      print 'Err: unable to find a list "%s"' % nodeAddr
      sys.exit(1)
  for i in data:
    line = []
    for j in fields:
      if j in i.keys():
        line.append(i[j].replace('\t', ' '))
      else:
        print 'Err: unable to find a field "%s"' % j
        sys.exit(1)
    print '\t'.join(line)
  sys.exit()

if __name__ == "__main__":
   main(sys.argv)